CREATE TABLE user (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100)
);

INSERT INTO user (name) VALUES ('Donald');

CREATE TABLE log (
	startNo BIGINT NOT NULL,
	endNo BIGINT NOT NULL,
	ctime DATETIME
);

